# Dependencies
markdown:         kramdown
kramdown:
    auto_ids: false
highlighter:      rouge

# Permalinks
permalink: /blog/:title

# Setup
title:            YXEpedition
tagline:          'A summer at Saskatoon (YXE)'
description:      'Experiences as a summer intern at University of Saskatchewan.'
url:              ''
baseurl:          ''
excerpt_separator: <!--more-->

author:
  name:           'Mythreyi Ramesh'          

paginate:         2
timezone: America/Regina

plugins:
  - jekyll-paginate
  - jekyll-gist