# Dependencies
markdown:         kramdown
kramdown:
    auto_ids: false
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Yxepedition
tagline:          'A summer at Saskatoon (YXE)'
description:      'My experiences as a summer intern at University of Saskatchewan.'
url:              ''
baseurl:          ''

author:
  name:           'Mythreyi Ramesh'          

paginate:         5
paginate_path: '/blog/page:num/'
permalink: /blog/:title

plugins:
  - jekyll-paginate
  - jekyll-gist